pipeline:
  name: handsonharness
  identifier: handsonharness
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: handsonharnessservice
          environment:
            environmentRef: harnessdevenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harness_k8sinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
    - stage:
        name: chaostesting
        identifier: chaostesting
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Chaos
                  name: Chaos_1
                  identifier: Chaos_1
                  spec:
                    experimentRef: chaos-experiment-1gk
                    expectedResilienceScore: 50
        tags: {}
